version: '3'

services:
  authentication_database_psql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${USER_POSTGRES_DB_NAME}
      POSTGRES_USER: ${USER_POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${USER_POSTGRES_DB_PASSWORD}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  authentication_service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - authentication_database_psql
    ports:
      - "9000-9002:9000"
    env_file:
      - .env

volumes:
  postgres_data:
