"""order and payment

Revision ID: 1bcbfcd47518
Revises: 1b0063024080
Create Date: 2024-08-05 23:18:40.273448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bcbfcd47518'
down_revision: Union[str, None] = '1b0063024080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('payment_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Orders', 'Payment', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Orders', type_='foreignkey')
    op.drop_column('Orders', 'payment_id')
    # ### end Alembic commands ###
