"""renamed

Revision ID: 1ff76957274e
Revises: 40209f648ff3
Create Date: 2024-08-06 12:40:14.968628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff76957274e'
down_revision: Union[str, None] = '40209f648ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Payment', sa.Column('payment_uuid', sa.String(), nullable=False))
    op.drop_column('Payment', 'payment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Payment', sa.Column('payment_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Payment', 'payment_uuid')
    # ### end Alembic commands ###
