"""removed token feature

Revision ID: 2a183e9a826a
Revises: a0f852c2cc31
Create Date: 2024-07-31 09:53:03.803460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a183e9a826a'
down_revision: Union[str, None] = 'a0f852c2cc31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_used_tokens_id', table_name='used_tokens')
    op.drop_index('ix_used_tokens_token', table_name='used_tokens')
    op.drop_table('used_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='used_tokens_pkey')
    )
    op.create_index('ix_used_tokens_token', 'used_tokens', ['token'], unique=True)
    op.create_index('ix_used_tokens_id', 'used_tokens', ['id'], unique=False)
    # ### end Alembic commands ###
