"""Add UserPayment table and relationship 2

Revision ID: 3dc6df019b70
Revises: 6942648292fb
Create Date: 2024-07-28 13:52:51.128022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dc6df019b70'
down_revision: Union[str, None] = '6942648292fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('amount_paid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_payments_amount_paid'), 'user_payments', ['amount_paid'], unique=False)
    op.create_index(op.f('ix_user_payments_id'), 'user_payments', ['id'], unique=False)
    op.create_index(op.f('ix_user_payments_payment_id'), 'user_payments', ['payment_id'], unique=True)
    op.create_index(op.f('ix_user_payments_payment_method'), 'user_payments', ['payment_method'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_payments_payment_method'), table_name='user_payments')
    op.drop_index(op.f('ix_user_payments_payment_id'), table_name='user_payments')
    op.drop_index(op.f('ix_user_payments_id'), table_name='user_payments')
    op.drop_index(op.f('ix_user_payments_amount_paid'), table_name='user_payments')
    op.drop_table('user_payments')
    # ### end Alembic commands ###
