"""removed order back reverse relation

Revision ID: 57704cdd5f0c
Revises: 1ff76957274e
Create Date: 2024-08-06 12:44:17.891835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57704cdd5f0c'
down_revision: Union[str, None] = '1ff76957274e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Payment', 'order_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Payment', sa.Column('order_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
