"""added deliver address and order notes

Revision ID: 5ced988c4452
Revises: 9a72b1f39ee4
Create Date: 2024-08-06 13:49:59.063481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ced988c4452'
down_revision: Union[str, None] = '9a72b1f39ee4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('delivery_address', sa.String(), nullable=False))
    op.add_column('Orders', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Orders', 'status')
    op.drop_column('Orders', 'delivery_address')
    # ### end Alembic commands ###
