"""total amount for each order

Revision ID: 72dea28d65f8
Revises: ede07629e279
Create Date: 2024-08-06 20:56:07.121568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72dea28d65f8'
down_revision: Union[str, None] = 'ede07629e279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderItems', sa.Column('total_amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OrderItems', 'total_amount')
    # ### end Alembic commands ###
