"""Added order and more

Revision ID: 80e88bf21c9b
Revises: 3dc6df019b70
Create Date: 2024-07-28 15:06:28.949396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e88bf21c9b'
down_revision: Union[str, None] = '3dc6df019b70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('is_delivered', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['user_payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_orders_address'), 'user_orders', ['address'], unique=False)
    op.create_index(op.f('ix_user_orders_id'), 'user_orders', ['id'], unique=False)
    op.create_index(op.f('ix_user_orders_price'), 'user_orders', ['price'], unique=False)
    op.create_index(op.f('ix_user_orders_product'), 'user_orders', ['product'], unique=False)
    op.create_index(op.f('ix_user_orders_quantity'), 'user_orders', ['quantity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_orders_quantity'), table_name='user_orders')
    op.drop_index(op.f('ix_user_orders_product'), table_name='user_orders')
    op.drop_index(op.f('ix_user_orders_price'), table_name='user_orders')
    op.drop_index(op.f('ix_user_orders_id'), table_name='user_orders')
    op.drop_index(op.f('ix_user_orders_address'), table_name='user_orders')
    op.drop_table('user_orders')
    # ### end Alembic commands ###
