"""change from int to str for phone

Revision ID: 8acc0963c6ea
Revises: 7c0bde7650ea
Create Date: 2024-04-28 21:57:25.140035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8acc0963c6ea'
down_revision: Union[str, None] = '7c0bde7650ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
