"""added amount

Revision ID: ae355643cece
Revises: 0081c9fafc68
Create Date: 2024-08-01 13:00:20.152082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae355643cece'
down_revision: Union[str, None] = '0081c9fafc68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Payment', sa.Column('payment_amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Payment', 'payment_amount')
    # ### end Alembic commands ###
