"""added order notes

Revision ID: cf8ed01cb0dd
Revises: 5ced988c4452
Create Date: 2024-08-06 14:18:56.303599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf8ed01cb0dd'
down_revision: Union[str, None] = '5ced988c4452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('order_note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Orders', 'order_note')
    # ### end Alembic commands ###
