"""adding the address field in Users table

Revision ID: d458c70c73bc
Revises: d286d5925802
Create Date: 2024-07-29 17:32:52.385394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd458c70c73bc'
down_revision: Union[str, None] = 'd286d5925802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('address', sa.String(length=225), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'address')
    # ### end Alembic commands ###
