"""created table for token

Revision ID: d9116c771ee5
Revises: 8acc0963c6ea
Create Date: 2024-04-30 13:02:46.489490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9116c771ee5'
down_revision: Union[str, None] = '8acc0963c6ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_used_tokens_id'), 'used_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_used_tokens_token'), 'used_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_used_tokens_token'), table_name='used_tokens')
    op.drop_index(op.f('ix_used_tokens_id'), table_name='used_tokens')
    op.drop_table('used_tokens')
    # ### end Alembic commands ###
