"""common table fix

Revision ID: e51d17b0c276
Revises: 522e5cc8c135
Create Date: 2024-08-06 19:43:44.065171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e51d17b0c276'
down_revision: Union[str, None] = '522e5cc8c135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Orders', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('Orders', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('Orders', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Orders', 'updated_at')
    op.drop_column('Orders', 'created_at')
    op.drop_column('Orders', 'is_deleted')
    # ### end Alembic commands ###
