"""new table

Revision ID: ede07629e279
Revises: e51d17b0c276
Create Date: 2024-08-06 19:44:26.757210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede07629e279'
down_revision: Union[str, None] = 'e51d17b0c276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderItems', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('OrderItems', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('OrderItems', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OrderItems', 'updated_at')
    op.drop_column('OrderItems', 'created_at')
    op.drop_column('OrderItems', 'is_deleted')
    # ### end Alembic commands ###
