"""change in OrderItems

Revision ID: efff6dfad111
Revises: 72dea28d65f8
Create Date: 2024-09-26 10:58:42.137538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efff6dfad111'
down_revision: Union[str, None] = '72dea28d65f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('OrderItems', sa.Column('color', sa.String(), nullable=True))
    op.add_column('OrderItems', sa.Column('size', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('OrderItems', 'size')
    op.drop_column('OrderItems', 'color')
    # ### end Alembic commands ###
